### ISSUE TITLE
Error with BTL201

### ISSUE THREAD

**Issue by sanyatuning** [D3M80L/hassio-mipow#10]
i got an exception when adding device

```
2022-12-15 16:41:56.149 ERROR (MainThread) [custom_components.mipow.config_flow] Failed to connect
Traceback (most recent call last):
  File "/config/custom_components/mipow/config_flow.py", line 58, in async_step_user
    await mipow.update()
  File "/config/custom_components/mipow/mipow.py", line 176, in update
    await self._client.read_gatt_char(self._battery_characteristic)
  File "/usr/local/lib/python3.10/site-packages/bleak/__init__.py", line 571, in read_gatt_char
    return await self._backend.read_gatt_char(char_specifier, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 679, in read_gatt_char
    assert_reply(reply)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 20, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.NotPermitted] Read not permitted
```

the self._battery_characteristic property had this value when I got the error
```
2022-12-15 17:05:56.266 DEBUG (MainThread) [custom_components.mipow.mipow] before if 00002a19-0000-1000-8000-00805f9b34fb (Handle: 35): Battery Level
```

after I commented out this line, the error gone, and the light is working
```
        #self._battery_characteristic = services.get_characteristic(
        #    "00002a19-0000-1000-8000-00805f9b34fb"
        #)
```

**Comment by D3M80L** [comment]
Thank you for the information. Good that you found a workaround. I see this is a non-battery powered device. Hope I will find some time this year and will prepare a fix for that. As I have no such hardware - could you please check if all other functionalities work as expected?

**Comment by sanyatuning** [comment]
Hi @D3M80L!

Sorry for the late answer but I still get the error
```
2023-01-21 10:25:33.784 DEBUG (MainThread) [custom_components.mipow] async_setup_entry 0D:A6:4B:11:AC:E6
2023-01-21 10:25:33.784 DEBUG (MainThread) [custom_components.mipow] _async_update_mipow <home_assistant_bluetooth.models.BluetoothServiceInfoBleak object at 0x7f5aac5b2940>
2023-01-21 10:25:33.785 DEBUG (MainThread) [custom_components.mipow.mipow] Update locked False
2023-01-21 10:25:34.428 DEBUG (MainThread) [custom_components.mipow.mipow] Enabling timer bytearray(b'\x00\x02\x01\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00')
2023-01-21 10:25:34.589 DEBUG (MainThread) [custom_components.mipow] Finished fetching MIPOW SMART BULB data in 0.803 seconds (success: False)
2023-01-21 10:25:34.589 DEBUG (MainThread) [custom_components.mipow] Config entry not ready for 0D:A6:4B:11:AC:E6
2023-01-21 10:25:34.589 WARNING (MainThread) [homeassistant.config_entries] Config entry 'MiPow MIPOW SMART BULB(0D:A6:4B:11:AC:E6)' for mipow integration not ready yet: [org.bluez.Error.NotPermitted] Read not permitted; Retrying in background
2023-01-21 10:25:39.668 DEBUG (MainThread) [custom_components.mipow] async_setup_entry 0D:A6:4B:11:AC:E6
2023-01-21 10:25:39.669 DEBUG (MainThread) [custom_components.mipow] _async_update_mipow <home_assistant_bluetooth.models.BluetoothServiceInfoBleak object at 0x7f5aac5b2940>
2023-01-21 10:25:39.670 DEBUG (MainThread) [custom_components.mipow.mipow] Update locked False
2023-01-21 10:25:40.348 DEBUG (MainThread) [custom_components.mipow.mipow] Enabling timer bytearray(b'\x00\x02\x01\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00')
2023-01-21 10:25:40.509 DEBUG (MainThread) [custom_components.mipow] Finished fetching MIPOW SMART BULB data in 0.839 seconds (success: False)
2023-01-21 10:25:40.510 DEBUG (MainThread) [custom_components.mipow] Config entry not ready for 0D:A6:4B:11:AC:E6
2023-01-21 10:25:50.701 DEBUG (MainThread) [custom_components.mipow] async_setup_entry 0D:A6:4B:11:AC:E6
2023-01-21 10:25:50.701 DEBUG (MainThread) [custom_components.mipow] _async_update_mipow <home_assistant_bluetooth.models.BluetoothServiceInfoBleak object at 0x7f5aac5b2940>
2023-01-21 10:25:50.702 DEBUG (MainThread) [custom_components.mipow.mipow] Update locked False
2023-01-21 10:25:51.349 DEBUG (MainThread) [custom_components.mipow.mipow] Enabling timer bytearray(b'\x00\x02\x01\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00')
2023-01-21 10:25:51.508 DEBUG (MainThread) [custom_components.mipow] Finished fetching MIPOW SMART BULB data in 0.807 seconds (success: False)
2023-01-21 10:25:51.509 DEBUG (MainThread) [custom_components.mipow] Config entry not ready for 0D:A6:4B:11:AC:E6
2023-01-21 10:25:57.979 DEBUG (MainThread) [custom_components.mipow.mipow] _execute_disconnect locked False
2023-01-21 10:26:11.956 DEBUG (MainThread) [custom_components.mipow] async_setup_entry 0D:A6:4B:11:AC:E6
2023-01-21 10:26:11.956 DEBUG (MainThread) [custom_components.mipow] _async_update_mipow <home_assistant_bluetooth.models.BluetoothServiceInfoBleak object at 0x7f5aac5b2940>
2023-01-21 10:26:11.956 DEBUG (MainThread) [custom_components.mipow.mipow] Update locked False
2023-01-21 10:26:12.630 DEBUG (MainThread) [custom_components.mipow.mipow] Enabling timer bytearray(b'\x00\x02\x01\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00')
2023-01-21 10:26:12.789 DEBUG (MainThread) [custom_components.mipow] Finished fetching MIPOW SMART BULB data in 0.832 seconds (success: False)
2023-01-21 10:26:12.789 DEBUG (MainThread) [custom_components.mipow] Config entry not ready for 0D:A6:4B:11:AC:E6
2023-01-21 10:26:32.581 DEBUG (MainThread) [custom_components.mipow.mipow] _execute_disconnect locked False
2023-01-21 10:26:38.820 DEBUG (MainThread) [custom_components.mipow.mipow] _execute_disconnect locked False
2023-01-21 10:26:52.709 DEBUG (MainThread) [custom_components.mipow.mipow] _execute_disconnect locked False
2023-01-21 10:26:52.917 DEBUG (MainThread) [custom_components.mipow] async_setup_entry 0D:A6:4B:11:AC:E6
2023-01-21 10:26:52.918 DEBUG (MainThread) [custom_components.mipow] _async_update_mipow <home_assistant_bluetooth.models.BluetoothServiceInfoBleak object at 0x7f5aac5b2940>
2023-01-21 10:26:52.918 DEBUG (MainThread) [custom_components.mipow.mipow] Update locked False
2023-01-21 10:26:53.590 DEBUG (MainThread) [custom_components.mipow.mipow] Enabling timer bytearray(b'\x00\x02\x01\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00')
2023-01-21 10:26:53.749 DEBUG (MainThread) [custom_components.mipow] Finished fetching MIPOW SMART BULB data in 0.831 seconds (success: False)
2023-01-21 10:26:53.749 DEBUG (MainThread) [custom_components.mipow] Config entry not ready for 0D:A6:4B:11:AC:E6
2023-01-21 10:26:54.950 WARNING (MainThread) [custom_components.mipow.mipow] MIPOW SMART BULB: Disconnected; RSSI: -127
2023-01-21 10:26:54.952 DEBUG (MainThread) [custom_components.mipow.mipow] MIPOW SMART BULB: Disconnected; RSSI: -127
2023-01-21 10:26:54.952 WARNING (MainThread) [custom_components.mipow.mipow] MIPOW SMART BULB: Disconnected; RSSI: -127
2023-01-21 10:26:54.953 WARNING (MainThread) [custom_components.mipow.mipow] MIPOW SMART BULB: Disconnected; RSSI: -127
2023-01-21 10:26:54.957 WARNING (MainThread) [custom_components.mipow.mipow] MIPOW SMART BULB: Disconnected; RSSI: -127
2023-01-21 10:26:54.962 WARNING (MainThread) [custom_components.mipow.mipow] MIPOW SMART BULB: Disconnected; RSSI: -127
2023-01-21 10:26:54.967 WARNING (MainThread) [custom_components.mipow.mipow] MIPOW SMART BULB: Disconnected; RSSI: -127
```

**Comment by sanyatuning** [comment]
on the UI i see this
![image](https://user-images.githubusercontent.com/2077907/213860872-b077e613-cf9b-49a1-9023-a97a8968cbec.png)

**Comment by sanyatuning** [comment]
I will create a pull request.

I also logged out these.
```
                    _LOGGER.warn(self._battery_characteristic)
                    _LOGGER.warn(self._battery_characteristic.properties)
```
output
```
2023-01-21 11:54:14.138 WARNING (MainThread) [custom_components.mipow.mipow] 00002a19-0000-1000-8000-00805f9b34fb (Handle: 35): Battery Level
2023-01-21 11:54:14.139 WARNING (MainThread) [custom_components.mipow.mipow] ['read', 'notify']
```
