### ISSUE TITLE
Home Assistant version 2022.7 bluepy breaking changes

### ISSUE THREAD

**Issue by tazomatalax** [D3M80L/hassio-mipow#5]
No longer working with the new update. Is there anyway to change the to Bleak library?

**Comment by D3M80L** [comment]
Yes, there is already a develop branch with the changes, still working on that, as few things do not work as expected.
Can't say when I will merge that, but want to do it within few days.

**Comment by tazomatalax** [comment]
Just updated to latest version but device still will not connect. 
Attached Logs:


`Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mipow/mipow.py:41
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 8:13:53 PM (13 occurrences)
Last logged: 8:37:14 PM

[2927592088] [Errno 2] No such file or directory
[2927592088] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 553, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/mipow/light.py", line 245, in async_turn_on
    await self._set_light(rgbw_color, effectId, transition, set_effect=effectSet)
  File "/config/custom_components/mipow/light.py", line 378, in _set_light
    await self._connect()
  File "/config/custom_components/mipow/light.py", line 337, in _connect
    await self._light.connect()
  File "/config/custom_components/mipow/mipow.py", line 41, in connect
    await self._device.connect(timeout = 9)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 112, in connect
    device = await BleakScannerBlueZDBus.find_device_by_address(
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/scanner.py", line 220, in find_device_by_address
    return await cls.find_device_by_filter(
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/scanner.py", line 249, in find_device_by_filter
    async with cls(detection_callback=apply_filter, **kwargs):
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/scanner.py", line 95, in __aenter__
    await self.start()
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/scanner.py", line 88, in start
    self._bus = await MessageBus(bus_type=BusType.SYSTEM).connect()
  File "/usr/local/lib/python3.10/site-packages/dbus_next/aio/message_bus.py", line 122, in __init__
    super().__init__(bus_address, bus_type, ProxyObject)
  File "/usr/local/lib/python3.10/site-packages/dbus_next/message_bus.py", line 85, in __init__
    self._setup_socket()
  File "/usr/local/lib/python3.10/site-packages/dbus_next/message_bus.py", line 575, in _setup_socket
    raise err
  File "/usr/local/lib/python3.10/site-packages/dbus_next/message_bus.py", line 548, in _setup_socket
    self._sock.connect(filename)
FileNotFoundError: [Errno 2] No such file or directory`

Is there anything else that needs do be done to enable bulb to reconnect to raspberry pi over bluetooth?

**Comment by D3M80L** [comment]
Interesting @tazomatalax, looks similar to the issue presented here with a different integration: https://community.home-assistant.io/t/switchbot-curtain/219837/158

**Comment by tazomatalax** [comment]
Nice one! Thanks mate.

Added:
`- /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket`
to volumes in docker-compose.yml
Works perfect again.
